"""Generates docs/diagrams/lora_architecture.png — the proposed LoRa hub/stop-unit
link diagram embedded in docs/radio_signalling_report.md, replacing ASCII art."""

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

BG = "#0d1117"
BOX_FACE = "#161b22"
BOX_EDGE = "#58a6ff"
TEXT = "#e6edf3"
SUBTEXT = "#8b949e"
ARROW = "#58a6ff"

fig, ax = plt.subplots(figsize=(10, 4))
fig.patch.set_facecolor(BG)
ax.set_facecolor(BG)
ax.set_xlim(0, 10)
ax.set_ylim(0, 4)
ax.axis("off")


def box(x, y, w, h, title, lines):
    patch = FancyBboxPatch(
        (x, y), w, h, boxstyle="round,pad=0.12,rounding_size=0.12",
        linewidth=1.6, edgecolor=BOX_EDGE, facecolor=BOX_FACE,
    )
    ax.add_patch(patch)
    ax.text(x + w / 2, y + h - 0.3, title, ha="center", va="top",
            color=TEXT, fontsize=10.5, fontweight="bold", family="monospace")
    for i, line in enumerate(lines):
        ax.text(x + w / 2, y + h - 0.62 - i * 0.27, line, ha="center", va="top",
                color=SUBTEXT, fontsize=8, family="monospace")
    return (x, y, w, h)


hub = box(0.4, 1.0, 3.6, 2.2, "CENTRAL HUB",
          ["Route optimiser +", "FastAPI backend", "(existing system)"])
stop = box(6.0, 1.0, 3.6, 2.2, "STOP UNIT (× N)",
           ["LoRa RX (UART)", "→ microcontroller/FPGA", "→ drives WS2812B LEDs"])

tx = FancyArrowPatch((hub[0] + hub[2], hub[1] + hub[3] * 0.65),
                     (stop[0], stop[1] + stop[3] * 0.65),
                     arrowstyle="-|>", color=ARROW, linewidth=1.6, mutation_scale=15)
ax.add_patch(tx)
ax.text(5.0, 2.85, "433 MHz — LoRa TX", ha="center", color=TEXT, fontsize=8.5, family="monospace")

ack = FancyArrowPatch((stop[0], stop[1] + stop[3] * 0.3),
                      (hub[0] + hub[2], hub[1] + hub[3] * 0.3),
                      arrowstyle="-|>", color=SUBTEXT, linewidth=1.3,
                      mutation_scale=13, linestyle="--")
ax.add_patch(ack)
ax.text(5.0, 1.32, "ack / telemetry (optional)", ha="center", color=SUBTEXT, fontsize=8, family="monospace")

ax.text(5.0, 3.7, "Proposed LoRa link — central hub to bus-stop display units",
        ha="center", color=TEXT, fontsize=11.5, fontweight="bold", family="monospace")
ax.text(5.0, 0.3, "generated by docs/diagrams/generate_lora_diagram.py",
        ha="center", color=SUBTEXT, fontsize=7, style="italic", family="monospace")

plt.tight_layout()
plt.savefig("docs/diagrams/lora_architecture.png", dpi=180, facecolor=BG, bbox_inches="tight")
print("Saved docs/diagrams/lora_architecture.png")
