"""Generates docs/diagrams/methodology.png — the "methodology at a glance"
diagram embedded in the main README, replacing the old ASCII version."""

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

BG = "#0d1117"
BOX_FACE = "#161b22"
BOX_EDGE = "#58a6ff"
TEXT = "#e6edf3"
SUBTEXT = "#8b949e"
ARROW = "#58a6ff"

fig, ax = plt.subplots(figsize=(13, 7.5))
fig.patch.set_facecolor(BG)
ax.set_facecolor(BG)
ax.set_xlim(0, 13)
ax.set_ylim(0, 8.7)
ax.axis("off")


def box(x, y, w, h, title, lines):
    patch = FancyBboxPatch(
        (x, y), w, h, boxstyle="round,pad=0.12,rounding_size=0.12",
        linewidth=1.6, edgecolor=BOX_EDGE, facecolor=BOX_FACE,
    )
    ax.add_patch(patch)
    ax.text(x + w / 2, y + h - 0.3, title, ha="center", va="top",
            color=TEXT, fontsize=10.5, fontweight="bold", family="monospace")
    for i, line in enumerate(lines):
        ax.text(x + 0.28, y + h - 0.58 - i * 0.235, line, ha="left", va="top",
                color=SUBTEXT, fontsize=7, family="monospace")
    return (x, y, w, h)


def arrow(b1, b2):
    x1, y1, w1, h1 = b1
    x2, y2, w2, h2 = b2
    a = FancyArrowPatch((x1 + w1, y1 + h1 / 2), (x2, y2 + h2 / 2),
                        arrowstyle="-|>", color=ARROW, linewidth=1.4,
                        mutation_scale=14, shrinkA=2, shrinkB=2)
    ax.add_patch(a)


inputs = box(0.4, 4.5, 3.7, 3.2, "REAL-WORLD INPUTS",
             ["• TfWM GTFS stops/roads",
              "• Open-Meteo weather", "  (2023–24 hourly)",
              "• UCL/GEoDS smartcard", "  journey volumes",
              "• Birmingham term dates",
              "• IMD 2019 / OSM POI /", "  police.uk / elevation",
              "• Census 2021"])

model = box(4.5, 4.5, 3.7, 3.2, "DEMAND MODEL",
            ["XGBoost regressor", "263k rows, 2023–24",
             "R² = 0.9421 (temporal", "  split, unseen 2024)", "",
             "predicts: boardings per", "stop, per hour, given", "conditions"])

optimiser = box(8.6, 4.5, 4.0, 3.2, "ROUTE OPTIMISER",
                ["Capacitated VRP", "greedy + 2-opt",
                 "1.16% gap vs. optimal", "< 2s solve time", "",
                 "outputs: per-scenario", "bus routes + real", "road geometry"])

arrow(inputs, model)
arrow(model, optimiser)

dashboard = box(2.6, 0.9, 3.6, 2.1, "WEB DASHBOARD",
                ["FastAPI + React/MapLibre", "live demand + routes +",
                 "equity overlay + story", "mode"])
fpga = box(6.8, 0.9, 3.6, 2.1, "FPGA LED MAP",
           ["physical, screen-free", "community-facing demand",
            "display at bus stops"])

src = (optimiser[0] + optimiser[2] / 2, optimiser[1])
for tgt in (dashboard, fpga):
    end = (tgt[0] + tgt[2] / 2, tgt[1] + tgt[3])
    a = FancyArrowPatch(src, end, arrowstyle="-|>", color=ARROW,
                        linewidth=1.3, mutation_scale=13, shrinkA=2, shrinkB=2)
    ax.add_patch(a)

ax.text(6.5, 8.5, "Methodology at a glance",
        ha="center", color=TEXT, fontsize=14, fontweight="bold", family="monospace")
ax.text(6.5, 8.18, "what feeds the model, and where every number in the README comes from",
        ha="center", color=SUBTEXT, fontsize=9, family="monospace")
ax.text(6.5, 0.35, "generated by docs/diagrams/generate_methodology_diagram.py",
        ha="center", color=SUBTEXT, fontsize=7.5, style="italic", family="monospace")

plt.tight_layout()
plt.savefig("docs/diagrams/methodology.png", dpi=180, facecolor=BG, bbox_inches="tight")
print("Saved docs/diagrams/methodology.png")
